### ISSUE TITLE
Add support for deploy-time linking

### ISSUE THREAD

**Issue by Karrq** [matter-labs/era-compiler-solidity#102]
#### 📝 Description

This features request is to port the existing `solc` support for deploy-time linking into `zksolc`.
`solc` achieves this by leaving placeholders in the bytecode to be filled in later (via itself or otherwise).

#### 🤔 Rationale

It allows tooling such as `foundry` and `hardhat` to deploy libraries in a temporary environment and link them to the contracts in use, without having to recompile everything, greatly improving UX.

#### 📋 Additional Context

This feature request comes from investigating the following issue on `foundry-zksync`: https://github.com/matter-labs/foundry-zksync/issues/382

* zksync docs on the non-support of the feature: https://docs.zksync.io/build/developer-reference/ethereum-differences/libraries
* `solc` docs on the library linking: https://docs.soliditylang.org/en/latest/using-the-compiler.html#library-linking

**Comment by hedgar2017** [comment]
Hey @Karrq, thank you for this request!

We're currently migrating to our new LLVM-based assembler and linker, and will think how to design this properly on our instruction set.

**Comment by hedgar2017** [comment]
Fully supported starting from v1.5.7: https://github.com/matter-labs/era-compiler-solidity/blob/main/docs/src/02-command-line-interface.md#--link

**Comment by Karrq** [comment]
Hey, thank you very much for adding this! Will definitely improve the UX for `foundry-zksync` :) 

While adding support for this, I noticed that unfortuantely it doesn't solve foundry's use case, because we need to be able to compile _all_ contracts, meanwhile as it currently stands we are not able to compile any dependency of an unlinked contract :(

**Comment by hedgar2017** [comment]
@Karrq thank you!
We already have the design for this use case, and I'll create an issue to track it shortly.
