### ISSUE TITLE
How to compile sol files to llvm ir files?

### ISSUE THREAD

**Issue by hrshy0629** [matter-labs/era-compiler-solidity#2]
As https://era.zksync.io/docs/dev/compiler-toolchain/overview.html#high-level-source-code-compilers mentioned, I first compiled the sol file to a yul file. I know this is the first step, but I could not compile the yul file to an LLVM ir file using Zksolc. What should I do?

**Comment by hedgar2017** [comment]
@hrshy0629 fixed in v1.3.9. The command from your last comment works now.

**Comment by hrshy0629** [comment]
Thanks a lot. I used `--system-mode` to generate readable `ll` files. I'll keep working on llvm and solidity.
