### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by hrshy0629** [matter-labs/era-compiler-solidity#7]
I ran into issues when I tried to compile from scratch from source code. At 7-2, `zkevm-llvm build` throws an error. I'm using ubuntu 22.04, clang, lld 13, rustc 1.67.1, solc 0.8.19. How can I avoid this mistake?
`FAILED: include/llvm/IR/IntrinsicsPowerPC.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsPowerPC.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=ppc -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsPowerPC.h -d include/llvm/IR/IntrinsicsPowerPC.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found`

**Comment by hrshy0629** [comment]
`[484/2119] Building Attributes.inc...
FAILED: include/llvm/IR/Attributes.inc /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/Attributes.inc
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-attrs -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Attributes.td --write-if-changed -o include/llvm/IR/Attributes.inc -d include/llvm/IR/Attributes.inc.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[485/2119] Building IntrinsicEnums.inc...
FAILED: include/llvm/IR/IntrinsicEnums.inc /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicEnums.inc
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicEnums.inc -d include/llvm/IR/IntrinsicEnums.inc.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[486/2119] Building IntrinsicImpl.inc...
FAILED: include/llvm/IR/IntrinsicImpl.inc /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicImpl.inc
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-impl -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicImpl.inc -d include/llvm/IR/IntrinsicImpl.inc.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[487/2119] Building IntrinsicsAArch64.h...
FAILED: include/llvm/IR/IntrinsicsAArch64.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsAArch64.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=aarch64 -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsAArch64.h -d include/llvm/IR/IntrinsicsAArch64.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[488/2119] Building IntrinsicsAMDGPU.h...
FAILED: include/llvm/IR/IntrinsicsAMDGPU.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsAMDGPU.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=amdgcn -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsAMDGPU.h -d include/llvm/IR/IntrinsicsAMDGPU.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[489/2119] Building IntrinsicsARM.h...
FAILED: include/llvm/IR/IntrinsicsARM.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsARM.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=arm -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsARM.h -d include/llvm/IR/IntrinsicsARM.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[490/2119] Building IntrinsicsBPF.h...
FAILED: include/llvm/IR/IntrinsicsBPF.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsBPF.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=bpf -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsBPF.h -d include/llvm/IR/IntrinsicsBPF.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[491/2119] Building IntrinsicsDirectX.h...
FAILED: include/llvm/IR/IntrinsicsDirectX.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsDirectX.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=dx -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsDirectX.h -d include/llvm/IR/IntrinsicsDirectX.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[492/2119] Building IntrinsicsHexagon.h...
FAILED: include/llvm/IR/IntrinsicsHexagon.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsHexagon.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=hexagon -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsHexagon.h -d include/llvm/IR/IntrinsicsHexagon.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[493/2119] Building IntrinsicsMips.h...
FAILED: include/llvm/IR/IntrinsicsMips.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsMips.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=mips -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsMips.h -d include/llvm/IR/IntrinsicsMips.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[494/2119] Building IntrinsicsNVPTX.h...
FAILED: include/llvm/IR/IntrinsicsNVPTX.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsNVPTX.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=nvvm -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsNVPTX.h -d include/llvm/IR/IntrinsicsNVPTX.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[495/2119] Building IntrinsicsPowerPC.h...
FAILED: include/llvm/IR/IntrinsicsPowerPC.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsPowerPC.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=ppc -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsPowerPC.h -d include/llvm/IR/IntrinsicsPowerPC.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[496/2119] Building IntrinsicsR600.h...
FAILED: include/llvm/IR/IntrinsicsR600.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsR600.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=r600 -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsR600.h -d include/llvm/IR/IntrinsicsR600.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[497/2119] Building IntrinsicsRISCV.h...
FAILED: include/llvm/IR/IntrinsicsRISCV.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsRISCV.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=riscv -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsRISCV.h -d include/llvm/IR/IntrinsicsRISCV.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[498/2119] Building IntrinsicsS390.h...
FAILED: include/llvm/IR/IntrinsicsS390.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsS390.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=s390 -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsS390.h -d include/llvm/IR/IntrinsicsS390.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[499/2119] Building IntrinsicsSPIRV.h...
FAILED: include/llvm/IR/IntrinsicsSPIRV.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsSPIRV.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=spv -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsSPIRV.h -d include/llvm/IR/IntrinsicsSPIRV.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[500/2119] Building IntrinsicsSyncVM.h...
FAILED: include/llvm/IR/IntrinsicsSyncVM.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsSyncVM.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=syncvm -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsSyncVM.h -d include/llvm/IR/IntrinsicsSyncVM.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
[501/2119] Building IntrinsicsVE.h...
FAILED: include/llvm/IR/IntrinsicsVE.h /home/shy/era-compiler-solidity/target-llvm/build-final/include/llvm/IR/IntrinsicsVE.h
cd /home/shy/era-compiler-solidity/target-llvm/build-final && /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen -gen-intrinsic-enums -intrinsic-prefix=ve -I /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR -I/home/shy/era-compiler-solidity/target-llvm/build-final/include -I/home/shy/era-compiler-solidity/llvm/llvm/include /home/shy/era-compiler-solidity/llvm/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsVE.h -d include/llvm/IR/IntrinsicsVE.h.d
/bin/sh: 1: /home/shy/era-compiler-solidity/target-llvm/build-final/NATIVE/bin/llvm-tblgen: not found
`

**Comment by hrshy0629** [comment]
`Zkevm-llvm` build as I understand it is the command executed in order to build the whole with zksolc frontend and zkevm backend. But it seems that when LLVM is built, the relevant parameters of LLVM are not configured? Is `llvm-tblgen` not usable?

**Comment by hrshy0629** [comment]
I think I know how to fix the above: the problems with 7.2 can be solved using musl-1.2.4; 8.b's problem needs sudo apt install musl-tools to solve! After these two steps, I finally compiled.

**Comment by hedgar2017** [comment]
@hrshy0629 sorry for the long reply!

Installing `musl-tools` is mentioned in `1.a` if you are going to build for musl.
