### ISSUE TITLE
Contract bytecode changes when the project context is altered

### ISSUE THREAD

**Issue by kiriyaga-txfusion** [matter-labs/era-compiler-solidity#75]
#### 📝 Description

The bytecode generated by zksolc compiler may vary in two scenarios: when compiling a contract solely with its dependent (imported) contracts, and when additional non-dependent contracts are added to the project.
When using the solc compiler, it consistently generates the same bytecode regardless of whether contracts are compiled solely with their dependent contracts or when non-dependent contracts are included in the project.

Knowing this, there were some projects where we couldn't verify the contract with the minimal contracts approach. When we sent only dependent contracts, the zksolc compiler on the verification backend generated different bytecode, resulting in an error: "Deployed bytecode is not equal to the generated one from a given source."
Sending the entire project context, including all contracts, allows the verification backend to compile the contracts successfully and verify the provided contract without encountering discrepancies in the bytecode.

#### 🔄 Reproduction Steps
**Repo**: https://github.com/ethereum-attestation-service/eas-contracts/tree/zksync
**Link to the issue**: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/507

1. Compile the minimal set of contracts required for verification and save a bytecode of EAS.sol contract. List of contracts: [
  "@openzeppelin/contracts/interfaces/IERC1271.sol",
  "@openzeppelin/contracts/interfaces/IERC5267.sol",
  "@openzeppelin/contracts/utils/Address.sol",
  "@openzeppelin/contracts/utils/ShortStrings.sol",
  "@openzeppelin/contracts/utils/StorageSlot.sol",
  "@openzeppelin/contracts/utils/Strings.sol",
  "@openzeppelin/contracts/utils/cryptography/ECDSA.sol",
  "@openzeppelin/contracts/utils/cryptography/EIP712.sol",
  "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol",
  "@openzeppelin/contracts/utils/math/Math.sol",
  "@openzeppelin/contracts/utils/math/SignedMath.sol",
  "contracts/EAS.sol",
  "contracts/IEAS.sol",
  "contracts/ISchemaRegistry.sol",
  "contracts/ISemver.sol",
  "contracts/Semver.sol",
  "contracts/eip1271/EIP1271Verifier.sol",
  "contracts/resolver/ISchemaResolver.sol",
]
2. Compile whole project contracts
3. Bytecodes for EAS.sol contract will not be same in both cases.

To achieve the first point in Hardhat, you can physically delete all unnecessary contracts. Alternatively, in the zksolc settings, you can specify contractsToCompile property.

```
zksolc: {
    version: '1.4.1',
    settings: {
      contractsToCompile: ['contracts/EAS.sol'],
      optimizer: {
        enabled: true,
        mode: '3',
      }
    }
  },
```

#### 🤔 Expected Behavior

The generated bytecode should remain consistent whether in a minimal context with dependent contracts or when non-dependent contracts are present in the project.

#### 😯 Current Behavior

The bytecode differs between minimal contexts (with dependent contracts) and projects containing non-dependent contracts.

#### 🖥️ Environment

This issue occurs locally within a Hardhat project running on Linux 18 and when utilizing a verification backend.

#### 📎 Log Output

Some bytecode differences:

![image](https://github.com/matter-labs/era-compiler-solidity/assets/131957563/886e4def-9aeb-4704-b263-ebf1e73ae0de)

**Comment by hedgar2017** [comment]
Hey @kiriyaga-txfusion, thanks for the report!
The bug is about non-determinism and will be easy for us to find.
Could you please create a repo with a minimal reproducible example out of your project?
Thanks!

**Comment by hedgar2017** [comment]
@kiriyaga-txfusion could you elaborate how to compile it locally?
`yarn` causes an error:
```
hedgarmac@MacBook-Pro-Oleksandr eas-contracts % yarn
yarn install v1.22.19
info No lockfile found.
(node:37032) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @nomicfoundation/edr-linux-x64-gnu@0.3.7: The platform "darwin" is incompatible with this module.
error @nomicfoundation/edr-linux-x64-gnu@0.3.7: The CPU architecture "arm64" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kiriyaga-txfusion** [comment]
Thanks for your response! In response to your question, I suggest using the pnpm package manager alongside Node.js version 18 for your specific case. Once you've set that up, you can proceed to compile the contracts by executing the command pnpm hardhat compile --network zksync. 

> Hey @kiriyaga-txfusion, thanks for the report! The bug is about non-determinism and will be easy for us to find. Could you specify the contract where see the different bytecode (the screenshot of log)? Thanks!

I compared the saved bytecode in the artifact file of the EAS.sol contract for both cases and also checked it after the compilation process in the debugger to ensure consistency.

**Comment by hedgar2017** [comment]
@kiriyaga-txfusion we've investigated the issue, and unfortunately it's a `solc` issue, because it produces different Yul in both cases:
[1.txt](https://github.com/matter-labs/era-compiler-solidity/files/15276656/1.txt)
[2.txt](https://github.com/matter-labs/era-compiler-solidity/files/15276654/2.txt)

**Comment by hedgar2017** [comment]
@kiriyaga-txfusion I believe it's only happening with the Yul codegen.
Could you try specifying the `--force-evmla` flag in the HH config?

**Comment by kiriyaga-txfusion** [comment]
@hedgar2017 With the forceEvmla flag, I successfully deployed a new contract and verified it with minimal contract context, which includes only the dependent contracts. However, I'm now considering how to handle already deployed contracts. Will we need to send all project contracts to generate an equal bytecode for verification?

**Comment by hedgar2017** [comment]
> @hedgar2017 With the forceEvmla flag, I successfully deployed a new contract and verified it with minimal contract context, which includes only the dependent contracts. However, I'm now considering how to handle already deployed contracts. Will we need to send all project contracts to generate an equal bytecode for verification?

Hey @perekopskiy, could you assist?

**Comment by perekopskiy** [comment]
> Will we need to send all project contracts to generate an equal bytecode for verification?

@kiriyaga-txfusion yes, that's the only option
