### ISSUE TITLE
Add support for inputs loaded via solc's import callbacks

### ISSUE THREAD

**Issue by elfedy** [matter-labs/era-compiler-solidity#98]
#### 📝 Description
When compiling a source file and finding an import that is not provided as input, `solc` will try to resolve the source via an [import callback](https://docs.soliditylang.org/en/latest/path-resolution.html#import-callback). If resolved successfully, the source will  be compiled and be part of the output. This is not something that zksolc apparently expects, as it fails [with this error](https://github.com/matter-labs/era-compiler-solidity/blob/e00d63b24ff6b040f1527295495b8f5459875bfa/src/project/mod.rs#L160). You can reproduce the behavior by following [these examples](https://github.com/elfedy/zksolc-loader-error-examples).
Ideally `zksolc` would be able to work just fine when it finds compiled outputs from `solc` that come from sources that are not part of the initial input. At least an attempt to reproduce the deafult `Host Filesystem Loader` that tries to get the file from the path derived from the source unit name would probably fit lots of use cases. If this is not possible or not planned to be supported, it would be nice to either use `solc` internally with `--no-import-callback` or give a clearer error explaining the user what happened a bit better (solc produced an output from a resolved import vs from a source provided on compiler input and this is not supported).  

#### 🤔 Rationale

Benefits from the feature would be:
1. Get closer to feature parity with solc.
2. User would not have to specify all sources as input to the compiler and just provide the "root" files.
3. Prevent some confusion on errors. There are cases that `solc` will add an already provided input but with a different name as a result of import resolution (It may have `home/user/Contract.sol` and `./Contract.sol` as different source units), in which case `zksolc` will fail when looking to the `sources` map with `Source code for path not found` even though a source code matching that path was provided as input.

#### 📋 Additional Context

This request comes as a result of investigating an issue in foundry: https://github.com/matter-labs/foundry-zksync/issues/411

After patching forge with an issue that did not add the correct `allow_paths`, using `forge build --zksync` on the [provided example](https://github.com/wshino/foundry-zksync-example) will result in the issue described in `.3` on the Rationale, where solc will resolve an import of an already provided source with a different source unit name, and then zksolc won't find the source by the path string of solc's output in the input provided by foundry.

**Comment by hedgar2017** [comment]
Will be released in v1.5.2!
